// POST /api/track — records one pageview into the D1 database.
// Cookie-free. For unique-visitor counting we store a daily-rotating one-way
// hash of (date + IP + user-agent); the raw IP is never stored, and the hash
// changes every day so it can't be used to follow someone over time.

const CREATE = `CREATE TABLE IF NOT EXISTS pageviews (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER NOT NULL,
  path TEXT NOT NULL,
  referrer TEXT,
  country TEXT,
  device TEXT,
  visitor TEXT
)`;

let schemaReady = false; // CREATE TABLE once per isolate, not on every pageview

// Only real site pages are recorded, so the endpoint can't be used to write
// arbitrary strings into the dashboard. Mirrors the files in the repo:
// index.html, prequel.html, and <lang>/index.html + <lang>/prequel/index.html
// (generated by tools/build-i18n.py). Several spellings per page because
// Cloudflare Pages serves clean URLs with and without trailing slashes.
const LANGS = ["es", "fa", "fr", "pt", "zh"];
const ALLOWED_PATHS = new Set(["/", "/index.html", "/prequel", "/prequel/", "/prequel.html"]);
for (const l of LANGS) {
  for (const p of ["", "/", "/index.html", "/prequel", "/prequel/", "/prequel/index.html"]) {
    ALLOWED_PATHS.add("/" + l + p);
  }
}

const MAX_BODY = 2048; // a real beacon is ~100 chars

async function visitorHash(request) {
  const ip = request.headers.get("cf-connecting-ip") || "";
  const ua = request.headers.get("user-agent") || "";
  const day = new Date().toISOString().slice(0, 10); // rotates daily (UTC)
  const data = new TextEncoder().encode(day + "|" + ip + "|" + ua + "|baylight-v1");
  const buf = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(buf)].slice(0, 8).map((b) => b.toString(16).padStart(2, "0")).join("");
}

export async function onRequestPost(context) {
  const { request, env } = context;
  if (!env.DB) return new Response(null, { status: 204 });

  if (Number(request.headers.get("content-length") || 0) > MAX_BODY) return new Response(null, { status: 204 });

  let body = {};
  try {
    const text = await request.text();
    if (text.length > MAX_BODY) return new Response(null, { status: 204 });
    body = JSON.parse(text) || {};
  } catch (_) {}

  const path = body && typeof body.path === "string" ? body.path : "";
  if (!ALLOWED_PATHS.has(path)) return new Response(null, { status: 204 }); // unknown path: drop silently

  let referrer = "";
  try { referrer = typeof body.referrer === "string" && body.referrer ? new URL(body.referrer).hostname.slice(0, 253) : ""; } catch (_) {}

  const country = (request.headers.get("cf-ipcountry") || "").slice(0, 8);
  const ua = request.headers.get("user-agent") || "";
  const device = /Mobi|Android|iPhone|iPad|iPod/i.test(ua) ? "mobile" : "desktop";
  const visitor = await visitorHash(request);

  const insert = () =>
    env.DB.prepare("INSERT INTO pageviews (ts, path, referrer, country, device, visitor) VALUES (?, ?, ?, ?, ?, ?)")
      .bind(Date.now(), path, referrer, country, device, visitor).run();

  try {
    if (!schemaReady) {
      await env.DB.prepare(CREATE).run();
      schemaReady = true;
    }
    try {
      await insert();
    } catch (_) {
      // Older DB created before the visitor column existed — add it once, then retry.
      try { await env.DB.prepare("ALTER TABLE pageviews ADD COLUMN visitor TEXT").run(); } catch (_) {}
      await insert();
    }
  } catch (_) {
    return new Response(null, { status: 204 }); // never break the page over analytics
  }
  return new Response(null, { status: 204 });
}
